### ISSUE TITLE
Reading off end of bitstring

### ISSUE THREAD

**Issue by ThNam203** [Eittipat/pyrtmp#19]
Hi,

I was trying to use the very first code example in Quickstart you provided. The server was up without problem, but it gave me this error when I tried to connect rtmp stream to the server (with obs and ffmpeg)

`DEBUG:pyrtmp.rtmp:Client connected 127.0.0.1:38948
ERROR:pyrtmp.rtmp:Reading off end of bitstring with fmt 'bytes:1528'. Only 10632 bits available.
Traceback (most recent call last):
  File "/home/sen1or/.local/lib/python3.10/site-packages/pyrtmp/rtmp.py", line 79, in client_callback
    await self.on_handshake(session)
  File "/home/sen1or/.local/lib/python3.10/site-packages/pyrtmp/rtmp.py", line 120, in on_handshake
    await session.handshake()
  File "/home/sen1or/.local/lib/python3.10/site-packages/pyrtmp/session_manager.py", line 56, in handshake
    await C2.from_stream(self.fifo_reader)
  File "/home/sen1or/.local/lib/python3.10/site-packages/pyrtmp/messages/handshake.py", line 57, in from_stream
    rand = await stream.read("bytes:1528")
  File "/home/sen1or/.local/lib/python3.10/site-packages/pyrtmp/__init__.py", line 42, in read
    value = self.buffer.read(fmt)
  File "/home/sen1or/.local/lib/python3.10/site-packages/bitstring/bitstream.py", line 356, in read
    raise bitstring.ReadError(f"Reading off end of bitstring with fmt '{fmt}'. Only {len(self) - p} bits available.")
bitstring.exceptions.ReadError: Reading off end of bitstring with fmt 'bytes:1528'. Only 10632 bits available.
DEBUG:pyrtmp.rtmp:Clean up 127.0.0.1:38948`

This is my environment:
Operating system: Linux Mint 21.3
Python version: 3.10.12
pyrtmp version: 0.3.0

Any feedback or help is much appreciated.

**Comment by ThNam203** [comment]
I just found a relevant issue, sorry for not checking #18
